#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -s "$HOME/.dotfiles/private/backups/PBACKUP/passphrase" ]]; then
  export BORG_KEYS_DIR=$HOME/.dotfiles/private/backups/keys
  export BORG_PASSPHRASE=`cat $HOME/.dotfiles/private/backups/PBACKUP/passphrase`
fi

export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
export PATH=$HOME/.cargo/bin:$HOME/.composer/vendor/bin:$HOME/Library/Python/2.7/bin:$PATH
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"

export VISUAL=vim
export EDITOR=emacs

# Node environments
## export NODENV_ROOT=/usr/local/var/nodenv
## if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

#unalias run-help
#autoload run-help
#HELPDIR=/usr/local/share/zsh/help

# export HOMEBREW_CASK_OPTS="--caskroom=/usr/local/Caskroom"

eval "$(/usr/local/bin/rbenv init -)"
