#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Mount secure volume if it exists
alias veracrypt='/Applications/Veracrypt.app/Contents/MacOS/Veracrypt --text'
#if [[ -d "$HOME/.dotfiles/private" ]]; then
#  echo ""
#else
#  if [[ -s "$HOME/.dotfiles/private.vc" ]]; then
#    # veracrypt $HOME/.dotfiles/private.vc $HOME/.dotfiles/private/
#    veracrypt --pim=485 -k "" --protect-hidden='no' $HOME/.dotfiles/private.vc $HOME/.dotfiles/private/
#  fi
#fi
alias privmnt='veracrypt --pim=485 -k "" --protect-hidden='no' $HOME/.dotfiles/private.vc $HOME/.dotfiles/private/'
alias privumnt='veracrypt -d $HOME/.dotfiles/private.vc'

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=~/.composer/vendor/bin:$PATH

# Keys / tokens
if [[ -s "$HOME/.dotfiles/private/api_keys/.keys" ]]; then
  source ~/.dotfiles/private/api_keys/.keys
fi
if [[ -s "$HOME/.dotfiles/private/backups/PBACKUP/passphrase" ]]; then
  export BORG_KEYS_DIR=$HOME/.dotfiles/private/backups/keys
  export BORG_PASSPHRASE=`cat $HOME/.dotfiles/private/backups/PBACKUP/passphrase`
fi

#export EDITOR=vim
export VISUAL=vim
export EDITOR=vim

# Node environemnts
export NODENV_ROOT=/usr/local/var/nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

#unalias run-help
#autoload run-help
#HELPDIR=/usr/local/share/zsh/help

eval "$(rbenv init -)"

export HOMEBREW_CASK_OPTS="--caskroom=/usr/local/Caskroom"

source /usr/local/share/zsh/site-functions/_aws

[ -f $HOME/.aliases ] && source $HOME/.aliases
