#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Mount secure volume if it exists
if [[ -d "$HOME/.dofiles/private" ]]; then
  echo "No secure volume mounted."
  if [[ -s "$HOME/.dotfiles/private.vc" ]]; then
    veracrypt ~/.dotfiles/private.vc ~/.dotfiles/private/
  fi
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=~/.composer/vendor/bin:$PATH

# Keys / tokens
source ~/.dotfiles/private/api_keys/.keys

#export EDITOR=vim
export VISUAL=vim
export EDITOR=vim

# Node environemnts
export NODENV_ROOT=/usr/local/var/nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

#unalias run-help
#autoload run-help
#HELPDIR=/usr/local/share/zsh/help

eval "$(rbenv init -)"

alias ll="ls -l"
alias emacs="~/Applications/Emacs.app/Contents/MacOS/Emacs -nw"
alias veracrypt='/Applications/Veracrypt.app/Contents/MacOS/Veracrypt --text'
