#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Mount secure volume if it exists
alias veracrypt='/Applications/Veracrypt.app/Contents/MacOS/Veracrypt --text'
if [[ -d "$HOME/.dotfiles/private" ]]; then
  echo ""
else
  if [[ -s "$HOME/.dotfiles/private.vc" ]]; then
    veracrypt ~/.dotfiles/private.vc ~/.dotfiles/private/
  fi
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=~/.composer/vendor/bin:$PATH

# Keys / tokens
source ~/.dotfiles/private/api_keys/.keys
if [[ -s "$HOME/.dotfiles/private/backups/PBACKUP/passphrase" ]]; then
  export BORG_KEYS_DIR=$HOME/.dotfiles/private/backups/keys
  export BORG_PASSPHRASE=`cat $HOME/.dotfiles/private/backups/PBACKUP/passphrase`
fi

#export EDITOR=vim
export VISUAL=vim
export EDITOR=vim

# Node environemnts
export NODENV_ROOT=/usr/local/var/nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

#unalias run-help
#autoload run-help
#HELPDIR=/usr/local/share/zsh/help

eval "$(rbenv init -)"

alias nom='npm cache clean && rm -rf node_modules && mkdir node_modules && touch node_modules/.metadata_never_index && npm install'
alias bom='bower cache clean && rm -rf bower_components && mkdir bower_components && touch bower_components/.metadata_never_index && bower install'

alias ll="ls -l"
alias emacs="~/Applications/Emacs.app/Contents/MacOS/Emacs -nw"
[ -f $HOME/.aliases ] && source $HOME/.aliases
